# Generated by Django 6.0.6 on 2026-06-17 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the transaction posted to the bank.')),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('gl_account', models.CharField(blank=True, default='', max_length=100)),
                ('qb_transaction_id', models.CharField(blank=True, db_index=True, help_text='Originating QuickBooks id, if derived from a GL transaction.', max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Deposit', 'Deposit'), ('JournalEntry', 'Journal Entry')], default='', max_length=20)),
            ],
            options={
                'ordering': ['-date', 'vendor'],
            },
        ),
        migrations.CreateModel(
            name='CloseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')])),
                ('summary_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed')], default='draft', max_length=10)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'close summaries',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Transaction date as recorded in QuickBooks.')),
                ('vendor', models.CharField(help_text='Payee / vendor name.', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in USD.', max_digits=12)),
                ('category', models.CharField(blank=True, default='', help_text='Expense/income category.', max_length=100)),
                ('gl_account', models.CharField(blank=True, default='', help_text='General ledger account.', max_length=100)),
                ('qb_transaction_id', models.CharField(db_index=True, help_text='QuickBooks transaction id; natural key for idempotent sync.', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Deposit', 'Deposit'), ('JournalEntry', 'Journal Entry')], help_text='QuickBooks record type.', max_length=20)),
            ],
            options={
                'ordering': ['-date', 'vendor'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('reconciliation', 'Reconciliation'), ('anomaly', 'Anomaly')], max_length=20)),
                ('reason', models.TextField(help_text='Human-readable explanation of the issue.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(blank=True, help_text='The bank transaction this flag concerns, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='core.banktransaction')),
                ('transaction', models.ForeignKey(blank=True, help_text='The GL transaction this flag concerns, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='core.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_transaction_id',
            field=models.ForeignKey(blank=True, help_text='The GL Transaction this bank entry was matched to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='core.transaction'),
        ),
    ]
