# Generated by Django 6.0.6 on 2026-06-19 20:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksCompany',
            fields=[
                ('realm_id', models.CharField(help_text='QuickBooks company/realm id.', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable company name (optional).', max_length=200)),
                ('is_connected', models.BooleanField(default=True, help_text='Whether this realm currently has stored tokens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'QuickBooks companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QBToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id (the sandbox realm for this build).', max_length=50, unique=True)),
                ('access_token_encrypted', models.TextField(help_text='Fernet-encrypted access token.')),
                ('refresh_token_encrypted', models.TextField(help_text='Fernet-encrypted refresh token.')),
                ('access_token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires.', null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, help_text='When the (long-lived) refresh token expires.', null=True)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='QuickBooks company these tokens belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='token', to='core.quickbookscompany')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this bank row belongs to.', max_length=50)),
                ('date', models.DateField(help_text='Date the transaction posted to the bank.')),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('gl_account', models.CharField(blank=True, default='', max_length=100)),
                ('qb_transaction_id', models.CharField(blank=True, db_index=True, help_text='Originating QuickBooks id, if derived from a GL transaction.', max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Deposit', 'Deposit'), ('JournalEntry', 'Journal Entry'), ('Bill', 'Bill'), ('BillPayment', 'Bill Payment'), ('VendorCredit', 'Vendor Credit')], default='', max_length=20)),
                ('company', models.ForeignKey(help_text='QuickBooks company this bank row belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='core.quickbookscompany')),
            ],
            options={
                'ordering': ['-date', 'vendor'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this balance belongs to.', max_length=50)),
                ('qb_account_id', models.CharField(db_index=True, help_text='QuickBooks account id (natural key scoped by realm).', max_length=50)),
                ('account_name', models.CharField(help_text='Account name as shown in QuickBooks; used to match GL transactions.', max_length=200)),
                ('month', models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')])),
                ('ending_balance', models.DecimalField(decimal_places=2, help_text='Ending balance shown on the bank statement for the account and month.', max_digits=12)),
                ('source', models.CharField(choices=[('qb_api', 'QuickBooks API'), ('manual', 'Manual entry'), ('csv_upload', 'CSV upload'), ('bank_feed', 'Bank feed')], default='manual', help_text='How this balance value was provided.', max_length=20)),
                ('statement_date', models.DateField(blank=True, help_text='Date the statement balance is as-of (usually the last day of the month).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='QuickBooks company this balance belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_balances', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'bank statement balance',
                'verbose_name_plural': 'bank statement balances',
                'ordering': ['-month', 'account_name'],
                'unique_together': {('company', 'qb_account_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this transaction belongs to.', max_length=50)),
                ('date', models.DateField(help_text='Transaction date as recorded in QuickBooks.')),
                ('vendor', models.CharField(help_text='Payee / vendor name.', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in USD.', max_digits=12)),
                ('category', models.CharField(blank=True, default='', help_text='Expense/income category.', max_length=100)),
                ('gl_account', models.CharField(blank=True, default='', help_text='General ledger account.', max_length=100)),
                ('qb_transaction_id', models.CharField(db_index=True, help_text='QuickBooks transaction id; natural key for idempotent sync (scoped by company).', max_length=100)),
                ('source_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Deposit', 'Deposit'), ('JournalEntry', 'Journal Entry'), ('Bill', 'Bill'), ('BillPayment', 'Bill Payment'), ('VendorCredit', 'Vendor Credit')], help_text='QuickBooks record type.', max_length=20)),
                ('company', models.ForeignKey(help_text='QuickBooks company this transaction belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.quickbookscompany')),
            ],
            options={
                'ordering': ['-date', 'vendor'],
                'unique_together': {('company', 'qb_transaction_id')},
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this flag belongs to.', max_length=50)),
                ('flag_type', models.CharField(choices=[('reconciliation', 'Reconciliation'), ('anomaly', 'Anomaly'), ('balance_reconciliation', 'Balance Reconciliation'), ('connectwise_unbilled', 'ConnectWise Unbilled'), ('connectwise_margin', 'ConnectWise Margin Erosion'), ('connectwise_missing_mapping', 'ConnectWise Missing Mapping')], max_length=30)),
                ('reason', models.TextField(help_text='Human-readable explanation of the issue.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional audit notes, e.g. what QuickBooks objects were created.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_statement_balance', models.ForeignKey(blank=True, help_text='For balance-reconciliation flags, the statement balance that triggered the flag.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.bankstatementbalance')),
                ('bank_transaction', models.ForeignKey(blank=True, help_text='The bank transaction this flag concerns, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='core.banktransaction')),
                ('company', models.ForeignKey(help_text='QuickBooks company this flag belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.quickbookscompany')),
                ('transaction', models.ForeignKey(blank=True, help_text='The GL transaction this flag concerns, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='core.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_transaction_id',
            field=models.ForeignKey(blank=True, help_text='The GL Transaction this bank entry was matched to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='core.transaction'),
        ),
        migrations.CreateModel(
            name='QBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this account belongs to.', max_length=50)),
                ('account_id', models.CharField(db_index=True, help_text='QuickBooks account id (natural key scoped by realm).', max_length=50)),
                ('name', models.CharField(help_text='Account name as shown in QBO.', max_length=200)),
                ('account_type', models.CharField(blank=True, default='', help_text='QuickBooks account type (e.g. Bank, Expense, Liability).', max_length=100)),
                ('account_sub_type', models.CharField(blank=True, default='', help_text='QuickBooks account sub-type.', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Whether QBO marks the account active.')),
                ('company', models.ForeignKey(help_text='QuickBooks company this account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'QuickBooks account',
                'verbose_name_plural': 'QuickBooks accounts',
                'ordering': ['name'],
                'unique_together': {('company', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='CloseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this summary belongs to.', max_length=50)),
                ('month', models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')])),
                ('summary_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed')], default='draft', max_length=10)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='QuickBooks company this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='close_summaries', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name_plural': 'close summaries',
                'ordering': ['-month'],
                'unique_together': {('company', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AccountReconciliationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this state belongs to.', max_length=50)),
                ('qb_account_id', models.CharField(db_index=True, help_text='QuickBooks account id (natural key scoped by realm).', max_length=50)),
                ('month', models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')])),
                ('statement_balance', models.DecimalField(decimal_places=2, help_text='Stored statement balance for the account and month.', max_digits=12)),
                ('posted_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Posted GL total at the time suggestions were generated.', max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statement balance minus posted GL total.', max_digits=12)),
                ('status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('in_progress', 'In Progress'), ('reconciled', 'Reconciled'), ('reviewed', 'Reviewed')], default='unreconciled', help_text='Current reconciliation status.', max_length=15)),
                ('reviewer_notes', models.TextField(blank=True, default='', help_text='Optional reviewer notes for the reconciliation.')),
                ('last_suggestions', models.JSONField(blank=True, default=dict, help_text='Cache of the latest LLM/deterministic suggestions.')),
                ('applied_suggestions', models.JSONField(blank=True, default=list, help_text='Suggestion ids that have already been applied to QuickBooks.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='QuickBooks company this reconciliation state belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_states', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'account reconciliation state',
                'verbose_name_plural': 'account reconciliation states',
                'ordering': ['-month', 'qb_account_id'],
                'unique_together': {('company', 'qb_account_id', 'month')},
            },
        ),
        migrations.CreateModel(
            name='QBCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this customer belongs to.', max_length=50)),
                ('customer_id', models.CharField(db_index=True, help_text='QuickBooks customer id (natural key scoped by realm).', max_length=50)),
                ('name', models.CharField(help_text='Customer name as shown in QBO.', max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Whether QBO marks the customer active.')),
                ('company', models.ForeignKey(help_text='QuickBooks company this customer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='qb_customers', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'QuickBooks customer',
                'verbose_name_plural': 'QuickBooks customers',
                'ordering': ['name'],
                'unique_together': {('company', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='ConnectWiseCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this ConnectWise company belongs to.', max_length=50)),
                ('connectwise_id', models.CharField(db_index=True, help_text='ConnectWise company id (natural key scoped by realm).', max_length=50)),
                ('name', models.CharField(help_text='ConnectWise company name.', max_length=200)),
                ('company', models.ForeignKey(help_text='QuickBooks company this ConnectWise company belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='connectwise_companies', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'ConnectWise company',
                'verbose_name_plural': 'ConnectWise companies',
                'ordering': ['name'],
                'unique_together': {('company', 'connectwise_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this mapping belongs to.', max_length=50)),
                ('billing_model', models.CharField(choices=[('hourly', 'Hourly / T&M'), ('flat_fee', 'Flat Fee / Managed Services'), ('retainer', 'Retainer')], default='hourly', help_text='Revenue model used for reconciliation.', max_length=20)),
                ('flat_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly flat-fee revenue target (required when billing_model=flat_fee).', max_digits=12, null=True)),
                ('default_burden_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-client default burden rate for time cost-to-serve.', max_digits=12, null=True)),
                ('company', models.ForeignKey(help_text='QuickBooks company this mapping belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='client_mappings', to='core.quickbookscompany')),
                ('connectwise_company', models.ForeignKey(help_text='ConnectWise company side of the mapping.', on_delete=django.db.models.deletion.CASCADE, related_name='client_mapping', to='core.connectwisecompany')),
                ('qbo_customer', models.ForeignKey(help_text='QuickBooks Online customer side of the mapping.', on_delete=django.db.models.deletion.CASCADE, related_name='client_mapping', to='core.qbcustomer')),
            ],
            options={
                'unique_together': {('company', 'connectwise_company'), ('company', 'qbo_customer')},
            },
        ),
        migrations.CreateModel(
            name='ConnectWiseWorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this role belongs to.', max_length=50)),
                ('role_name', models.CharField(help_text='ConnectWise work role name.', max_length=100)),
                ('burden_rate', models.DecimalField(decimal_places=2, help_text='Fully-loaded hourly cost for this role.', max_digits=12)),
                ('company', models.ForeignKey(help_text='QuickBooks company this role belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='connectwise_work_roles', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'ConnectWise work role',
                'verbose_name_plural': 'ConnectWise work roles',
                'ordering': ['role_name'],
                'unique_together': {('company', 'role_name')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this invoice belongs to.', max_length=50)),
                ('qb_invoice_id', models.CharField(db_index=True, help_text='QuickBooks invoice id (natural key scoped by realm).', max_length=50)),
                ('customer_name', models.CharField(help_text='Denormalized customer name for fast display.', max_length=200)),
                ('invoice_date', models.DateField(help_text='Invoice date as recorded in QBO.')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount in USD.', max_digits=12)),
                ('company', models.ForeignKey(help_text='QuickBooks company this invoice belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.quickbookscompany')),
                ('customer', models.ForeignKey(help_text='QBO customer this invoice is billed to.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.qbcustomer')),
            ],
            options={
                'ordering': ['-invoice_date', 'customer_name'],
                'unique_together': {('company', 'qb_invoice_id')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this line belongs to.', max_length=50)),
                ('line_number', models.PositiveIntegerField(help_text='Line number within the invoice.')),
                ('description', models.TextField(blank=True, default='', help_text='Line description.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Line amount in USD.', max_digits=12)),
                ('service_item', models.CharField(blank=True, default='', help_text='QBO service item name, if available.', max_length=200)),
                ('company', models.ForeignKey(help_text='QuickBooks company this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='core.quickbookscompany')),
                ('invoice', models.ForeignKey(help_text='Invoice this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice')),
            ],
            options={
                'ordering': ['invoice', 'line_number'],
                'unique_together': {('company', 'invoice', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this time entry belongs to.', max_length=50)),
                ('connectwise_entry_id', models.CharField(db_index=True, help_text='ConnectWise time entry id (natural key scoped by realm).', max_length=50)),
                ('agreement_name', models.CharField(blank=True, default='', help_text='ConnectWise agreement name, if available.', max_length=200)),
                ('ticket_number', models.CharField(blank=True, default='', help_text='ConnectWise ticket number, if available.', max_length=50)),
                ('technician', models.CharField(help_text='Technician who logged the time.', max_length=100)),
                ('date', models.DateField(help_text='Date the time was logged.')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours logged.', max_digits=8)),
                ('billable_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly billable rate, if known.', max_digits=12, null=True)),
                ('work_role', models.CharField(blank=True, default='', help_text='ConnectWise work role for burden-rate lookup.', max_length=100)),
                ('is_billable', models.BooleanField(default=True, help_text='Whether the time entry is billable.')),
                ('company', models.ForeignKey(help_text='QuickBooks company this time entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='connectwise_time_entries', to='core.quickbookscompany')),
                ('connectwise_company', models.ForeignKey(help_text='ConnectWise company this time entry is for.', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.connectwisecompany')),
            ],
            options={
                'ordering': ['-date', 'connectwise_company', 'technician'],
                'unique_together': {('company', 'connectwise_entry_id')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this expense entry belongs to.', max_length=50)),
                ('connectwise_entry_id', models.CharField(db_index=True, help_text='ConnectWise expense entry id (natural key scoped by realm).', max_length=50)),
                ('agreement_name', models.CharField(blank=True, default='', help_text='ConnectWise agreement name, if available.', max_length=200)),
                ('date', models.DateField(help_text='Date the expense was logged.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in USD.', max_digits=12)),
                ('description', models.CharField(blank=True, default='', help_text='Expense description.', max_length=255)),
                ('company', models.ForeignKey(help_text='QuickBooks company this expense entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='connectwise_expense_entries', to='core.quickbookscompany')),
                ('connectwise_company', models.ForeignKey(help_text='ConnectWise company this expense entry is for.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='core.connectwisecompany')),
            ],
            options={
                'ordering': ['-date', 'connectwise_company'],
                'unique_together': {('company', 'connectwise_entry_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this product entry belongs to.', max_length=50)),
                ('connectwise_entry_id', models.CharField(db_index=True, help_text='ConnectWise product entry id (natural key scoped by realm).', max_length=50)),
                ('agreement_name', models.CharField(blank=True, default='', help_text='ConnectWise agreement name, if available.', max_length=200)),
                ('date', models.DateField(help_text='Date the product was logged.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Product amount in USD.', max_digits=12)),
                ('description', models.CharField(blank=True, default='', help_text='Product description.', max_length=255)),
                ('company', models.ForeignKey(help_text='QuickBooks company this product entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='connectwise_product_entries', to='core.quickbookscompany')),
                ('connectwise_company', models.ForeignKey(help_text='ConnectWise company this product entry is for.', on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='core.connectwisecompany')),
            ],
            options={
                'ordering': ['-date', 'connectwise_company'],
                'unique_together': {('company', 'connectwise_entry_id')},
            },
        ),
    ]
