# Generated by Django 6.0.6 on 2026-06-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QBToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id (the sandbox realm for this build).', max_length=50, unique=True)),
                ('access_token_encrypted', models.TextField(help_text='Fernet-encrypted access token.')),
                ('refresh_token_encrypted', models.TextField(help_text='Fernet-encrypted refresh token.')),
                ('access_token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires.', null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, help_text='When the (long-lived) refresh token expires.', null=True)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
