# Generated by Django 6.0.6 on 2026-06-19 00:40

import django.core.validators
from django.db import migrations, models


def _backfill_realm_id(apps, schema_editor):
    """Backfill nullable realm_id columns from the most recently updated QBToken."""
    QBToken = apps.get_model("core", "QBToken")
    token = QBToken.objects.order_by("-updated_at").first()
    realm_id = token.realm_id if token else "legacy"

    for model_name in ("Transaction", "BankTransaction", "Flag", "CloseSummary"):
        Model = apps.get_model("core", model_name)
        Model.objects.filter(realm_id__isnull=True).update(realm_id=realm_id)


def _noop(apps, schema_editor):
    """No-op reverse migration; realm_id values remain as they are."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qbtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksCompany',
            fields=[
                ('realm_id', models.CharField(help_text='QuickBooks company/realm id.', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable company name (optional).', max_length=200)),
                ('is_connected', models.BooleanField(default=True, help_text='Whether this realm currently has stored tokens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'QuickBooks companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='realm_id',
            field=models.CharField(blank=True, db_index=True, help_text='QuickBooks company/realm id this bank row belongs to.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='closesummary',
            name='realm_id',
            field=models.CharField(blank=True, db_index=True, help_text='QuickBooks company/realm id this summary belongs to.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='realm_id',
            field=models.CharField(blank=True, db_index=True, help_text='QuickBooks company/realm id this flag belongs to.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='realm_id',
            field=models.CharField(blank=True, db_index=True, help_text='QuickBooks company/realm id this transaction belongs to.', max_length=50, null=True),
        ),
        migrations.RunPython(_backfill_realm_id, _noop),
        migrations.AlterField(
            model_name='banktransaction',
            name='realm_id',
            field=models.CharField(db_index=True, help_text='QuickBooks company/realm id this bank row belongs to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='closesummary',
            name='realm_id',
            field=models.CharField(db_index=True, help_text='QuickBooks company/realm id this summary belongs to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='flag',
            name='realm_id',
            field=models.CharField(db_index=True, help_text='QuickBooks company/realm id this flag belongs to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='realm_id',
            field=models.CharField(db_index=True, help_text='QuickBooks company/realm id this transaction belongs to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='closesummary',
            name='month',
            field=models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qb_transaction_id',
            field=models.CharField(db_index=True, help_text='QuickBooks transaction id; natural key for idempotent sync (scoped by realm_id).', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='closesummary',
            unique_together={('realm_id', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('realm_id', 'qb_transaction_id')},
        ),
    ]
