# Generated by Django 6.0.6 on 2026-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quickbookscompany_banktransaction_realm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='source_type',
            field=models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Deposit', 'Deposit'), ('JournalEntry', 'Journal Entry'), ('Bill', 'Bill'), ('BillPayment', 'Bill Payment'), ('VendorCredit', 'Vendor Credit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Deposit', 'Deposit'), ('JournalEntry', 'Journal Entry'), ('Bill', 'Bill'), ('BillPayment', 'Bill Payment'), ('VendorCredit', 'Vendor Credit')], help_text='QuickBooks record type.', max_length=20),
        ),
        migrations.CreateModel(
            name='QBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this account belongs to.', max_length=50)),
                ('account_id', models.CharField(db_index=True, help_text='QuickBooks account id (natural key scoped by realm).', max_length=50)),
                ('name', models.CharField(help_text='Account name as shown in QBO.', max_length=200)),
                ('account_type', models.CharField(blank=True, default='', help_text='QuickBooks account type (e.g. Bank, Expense, Liability).', max_length=100)),
                ('account_sub_type', models.CharField(blank=True, default='', help_text='QuickBooks account sub-type.', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Whether QBO marks the account active.')),
            ],
            options={
                'verbose_name': 'QuickBooks account',
                'verbose_name_plural': 'QuickBooks accounts',
                'ordering': ['name'],
                'unique_together': {('realm_id', 'account_id')},
            },
        ),
    ]
