# Generated by Django 6.0.6 on 2026-06-19 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qbaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='flag_type',
            field=models.CharField(choices=[('reconciliation', 'Reconciliation'), ('anomaly', 'Anomaly'), ('balance_reconciliation', 'Balance Reconciliation')], max_length=25),
        ),
        migrations.CreateModel(
            name='BankStatementBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this balance belongs to.', max_length=50)),
                ('qb_account_id', models.CharField(db_index=True, help_text='QuickBooks account id (natural key scoped by realm).', max_length=50)),
                ('account_name', models.CharField(help_text='Account name as shown in QuickBooks; used to match GL transactions.', max_length=200)),
                ('month', models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')])),
                ('ending_balance', models.DecimalField(decimal_places=2, help_text='Ending balance shown on the bank statement for the account and month.', max_digits=12)),
                ('source', models.CharField(choices=[('qb_api', 'QuickBooks API'), ('manual', 'Manual entry'), ('csv_upload', 'CSV upload'), ('bank_feed', 'Bank feed')], default='manual', help_text='How this balance value was provided.', max_length=20)),
                ('statement_date', models.DateField(blank=True, help_text='Date the statement balance is as-of (usually the last day of the month).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bank statement balance',
                'verbose_name_plural': 'bank statement balances',
                'ordering': ['-month', 'account_name'],
                'unique_together': {('realm_id', 'qb_account_id', 'month')},
            },
        ),
        migrations.AddField(
            model_name='flag',
            name='bank_statement_balance',
            field=models.ForeignKey(blank=True, help_text='For balance-reconciliation flags, the statement balance that triggered the flag.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.bankstatementbalance'),
        ),
    ]
