# Generated by Django 6.0.6 on 2026-06-19 17:14

import django.db.models.deletion
from django.db import migrations, models


def _backfill_company(apps, schema_editor, model_name):
    """Create QuickBooksCompany rows as needed and link all realm-scoped rows."""
    model = apps.get_model("core", model_name)
    company_model = apps.get_model("core", "QuickBooksCompany")
    realm_ids = (
        model.objects.filter(company__isnull=True)
        .values_list("realm_id", flat=True)
        .distinct()
    )
    for realm_id in realm_ids:
        company, _ = company_model.objects.get_or_create(
            realm_id=realm_id,
            defaults={"name": "", "is_connected": True},
        )
        model.objects.filter(realm_id=realm_id, company__isnull=True).update(
            company=company
        )


def _clear_company_fk(apps, schema_editor, model_name):
    """Reverse of the backfill: leave company FKs empty."""
    model = apps.get_model("core", model_name)
    model.objects.update(company=None)


REALM_SCOPED_MODELS = [
    "qbaccount",
    "bankstatementbalance",
    "transaction",
    "banktransaction",
    "flag",
    "closesummary",
    "qbtoken",
]


def backfill_companies(apps, schema_editor):
    for model_name in REALM_SCOPED_MODELS:
        _backfill_company(apps, schema_editor, model_name)


def clear_company_fks(apps, schema_editor):
    for model_name in REALM_SCOPED_MODELS:
        _clear_company_fk(apps, schema_editor, model_name)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_flag_flag_type_bankstatementbalance_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankstatementbalance",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="closesummary",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="qbaccount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bankstatementbalance",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company this balance belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_statement_balances",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company this bank row belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transactions",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AddField(
            model_name="closesummary",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company this summary belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="close_summaries",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AddField(
            model_name="flag",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company this flag belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AddField(
            model_name="qbaccount",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company this account belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AddField(
            model_name="qbtoken",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company these tokens belong to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="QuickBooks company this transaction belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.quickbookscompany",
            ),
        ),
        migrations.RunPython(backfill_companies, clear_company_fks),
        migrations.AlterField(
            model_name="bankstatementbalance",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company this balance belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_statement_balances",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company this bank row belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transactions",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="closesummary",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company this summary belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="close_summaries",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="flag",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company this flag belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="qbaccount",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company this account belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="qbtoken",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company these tokens belong to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="company",
            field=models.ForeignKey(
                help_text="QuickBooks company this transaction belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.quickbookscompany",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="qb_transaction_id",
            field=models.CharField(
                db_index=True,
                help_text="QuickBooks transaction id; natural key for idempotent sync (scoped by company).",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankstatementbalance",
            unique_together={("company", "qb_account_id", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="closesummary",
            unique_together={("company", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="qbaccount",
            unique_together={("company", "account_id")},
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("company", "qb_transaction_id")},
        ),
    ]
