# Generated by Django 6.0.6 on 2026-06-19 18:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bankstatementbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional audit notes, e.g. what QuickBooks objects were created.'),
        ),
        migrations.CreateModel(
            name='AccountReconciliationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, help_text='QuickBooks company/realm id this state belongs to.', max_length=50)),
                ('qb_account_id', models.CharField(db_index=True, help_text='QuickBooks account id (natural key scoped by realm).', max_length=50)),
                ('month', models.CharField(help_text='The close month in YYYY-MM format.', max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Month must be in YYYY-MM format.')])),
                ('statement_balance', models.DecimalField(decimal_places=2, help_text='Stored statement balance for the account and month.', max_digits=12)),
                ('posted_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Posted GL total at the time suggestions were generated.', max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statement balance minus posted GL total.', max_digits=12)),
                ('status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('in_progress', 'In Progress'), ('reconciled', 'Reconciled'), ('reviewed', 'Reviewed')], default='unreconciled', help_text='Current reconciliation status.', max_length=15)),
                ('reviewer_notes', models.TextField(blank=True, default='', help_text='Optional reviewer notes for the reconciliation.')),
                ('last_suggestions', models.JSONField(blank=True, default=dict, help_text='Cache of the latest LLM/deterministic suggestions.')),
                ('applied_suggestions', models.JSONField(blank=True, default=list, help_text='Suggestion ids that have already been applied to QuickBooks.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='QuickBooks company this reconciliation state belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_states', to='core.quickbookscompany')),
            ],
            options={
                'verbose_name': 'account reconciliation state',
                'verbose_name_plural': 'account reconciliation states',
                'ordering': ['-month', 'qb_account_id'],
                'unique_together': {('company', 'qb_account_id', 'month')},
            },
        ),
    ]
