"""
Django settings for the ``close_assistant`` project (Monthly Close Assistant).

Secrets and environment-specific values are loaded from environment variables (and a
local, gitignored ``.env`` file) via ``python-decouple``. See ``.env.example`` for the
full list and where each value comes from.

Generated by ``django-admin startproject`` (Django 6.0.6) and adapted for Postgres +
HTMX in Prompt 1 of the build.
"""
from __future__ import annotations

from pathlib import Path

from celery.schedules import crontab
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings.py lives in <repo_root>/close_assistant/, so BASE_DIR is the repo root.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "django_htmx",
    # Local
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Third-party: exposes ``request.htmx`` for detecting HTMX requests.
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "close_assistant.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "close_assistant.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL, configured entirely from environment variables via python-decouple so no
# connection details are committed to the repo.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Collected static files land here (gitignored); used by collectstatic in later stages.
STATIC_ROOT = BASE_DIR / "staticfiles"


# QuickBooks OAuth tokens are encrypted at rest with a Fernet symmetric key. When
# unset, tokens pass through in plaintext (dev only — a warning is emitted). Prompt 3.
QB_TOKEN_ENCRYPTION_KEY = config("QB_TOKEN_ENCRYPTION_KEY", default="")

# QuickBooks API environment: "sandbox" or "production". Prompt 4.
QB_ENVIRONMENT = config("QB_ENVIRONMENT", default="sandbox")

# How many minutes before access-token expiry to treat it as expired and refresh.
# Prompt 4.
QB_TOKEN_REFRESH_BUFFER_MINUTES = config("QB_TOKEN_REFRESH_BUFFER_MINUTES", default=15, cast=int)


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Celery + Redis task queue (Prompt 12)
# ---------------------------------------------------------------------------

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://localhost:6379/0"
)

# Run tasks synchronously when this is True (useful for tests / CI).
CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=False, cast=bool)

# Nightly scheduled tasks.
CELERY_BEAT_SCHEDULE = {
    "sync-quickbooks-nightly": {
        "task": "core.tasks.sync_quickbooks_task",
        "schedule": crontab(hour=0, minute=0),
    },
}
